version: '3'
services:
  node:
    build: .
    restart: always
    volumes:
      - ./src:/root
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
